### ISSUE TITLE
figure4 parameter estimates

### ISSUE THREAD

**Issue by Farnazmdi** [meyer-lab/lineage-growth#136]
@namn12 @shak360 [figure4](https://transduc.seas.ucla.edu/job/meyer-lab/job/lineage-growth/job/master/lastSuccessfulBuild/artifact/manuscript/figures/figure4.pdf) This is what I was talking about.

**Comment by shak360** [comment]
If this problem persists for more runs (n=200), then it's an issue.

**Comment by namn12** [comment]
what branch are u on . can i see the codde

**Comment by Farnazmdi** [comment]
![image](https://user-images.githubusercontent.com/34812750/61011600-0fc77b80-a330-11e9-882a-522aa2a9c5ef.png)
The master

**Comment by Farnazmdi** [comment]
> If this problem persists for more runs (n=200), then it's an issue.

@shak360 ok I saw it, and just thought if it is an issue we could address it

**Comment by shak360** [comment]
@namn12 See PR #137

**Comment by shak360** [comment]
![image](https://user-images.githubusercontent.com/20716101/61015738-c4b66400-a341-11e9-8b90-214ff10c88d2.png)

yea something needs to be fixed

**Comment by shak360** [comment]
![image](https://user-images.githubusercontent.com/20716101/61092164-0f93b280-a3fa-11e9-8703-26b2375d6781.png)
Should be fixed. There was an issue with the way bernoulli is initialized. When you initilize Bernoulli with `np.random.uniform()` it turns out really badly like the post from earlier. However, when you initialize with 0.5 you get the results in this post above.

**Comment by shak360** [comment]
Resolved.
