### ISSUE TITLE
Figure axes, labels, values

### ISSUE THREAD

**Issue by shak360** [meyer-lab/lineage-growth#226]
Some of the figures have trivial issues that can be easily corrected:
- incorrect naming
- double naming (some subplots are named the same thing)
- the values for the axes are colliding 
- the subplots themselves are colliding

**Comment by jclagarde** [comment]
Figure 1
- The values are overlapping

Figure 2
- Should the first letter of every word in the titles/axes be capitalized?
- Include a color key for all graphs
-Stylistic preference but possibly change the font to Times New Roman
-The graphs are too close to each other

Figure 3 & 4
- The graphs are too close to each other
- The titles should be more descriptive of what the graphs represent
- Same comment about font and color key as above

Figure 5
- The Graphs are too close together
- Write out what AlC stands for
- If relevant, maybe have each of the lines be a different color with a key included
- Include another number at the top of the y-axis of the third graph from the left since the lines are above the last value by a lot

Figure 6
- values of the x-axis of the second graph are colliding

**Comment by shak360** [comment]
#281 and #279
