### ISSUE TITLE
Allow for specific parameter sets to be fixed

### ISSUE THREAD

**Issue by aarmey** [meyer-lab/lineage-growth#267]
This can then be applied in Fig. 3 for the initial probabilities, since these are impossible to estimate with one starting cell.

**Comment by shak360** [comment]
Attacking this straight on will be a little difficult so let's try to work up to it @jclagarde. First, I want to make sure that you understand what it means to fix a parameter for estimation, so I want you to do a trivial problem that can show me that you understand. I'm going to try and give you less help this time, because I also want you to focus on using Google, StackExchange, documentation, etc. to help you write the code.

Use the following imports:

```python
from scipy.stats import gamma
import matplotlib.pyplot as plt
%matplotlib inline
```

1. In a Jupyter notebook, using `gamma.rv`, generate a 1000 random numbers from the gamma distribution using the following parameters: `a=10, loc=2, scale=1`. Use the documentation here: https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.gamma.html to help you.

2. Plot a histogram of these values using `matplotlib`. Use the documentation here: https://matplotlib.org/3.1.0/api/_as_gen/matplotlib.pyplot.hist.html to help you. You also plotted histograms in previous exercises, so this shouldn't be new.

3. Write a function that takes in gamma distribution parameters (`a, loc, scale`), generates and returns a 1000 random numbers and then plots the histogram of the data. Basically, package the previous steps into one function that you can call in the future. Call the function and store the generated numbers in a variable called `x`.

4. Using the generated random numbers, use the following line to estimate the parameters that created this distribution:

```python
a1, loc1, scale1 = gamma.fit(x)
```

5. Compare the values of `a1, loc1, scale1` to `a, loc, scale`. Make a quantitative and qualitative assessment of the estimation of these parameters. You can make a qualitative assessment by generating a new set of randomly generated numbers, and plot the histogram. This is as simple as calling the function you wrote on `a1, loc1, scale1`. A quantitative assessment could be some form of error or difference between the values themselves.

6. Given that we do know the parameters that generated those numbers, i.e., `a=10, loc=2, scale=1`, let's use this prior knowledge to better this estimation. We can do this by "freezing" or "fixing" the parameters so that our estimator knows that these parameters need not be changed when finding the optimal set of parameters. In scipy, this is as easy as the following:

```python
a2, loc2, scale2 = gamma.fit(x, floc=loc, fscale=scale)
```

7. Repeat step 5, with the new set of parameters, you've just estimated. Is the estimation of the `a` parameter better or worse? Make the same qualitative and quantitative assessments as before.

8. Our project involves generating lineages. What are the three important parameters that generate lineages? A good place to start is to look at the `lineageTree` class `init()` function in the `LineageTree.py` file.

**Comment by jclagarde** [comment]
<img width="1440" alt="Screen Shot 2020-04-06 at 7 36 00 PM" src="https://user-images.githubusercontent.com/54101546/78624275-1a229180-783e-11ea-80e9-f41161501165.png">
<img width="1440" alt="Screen Shot 2020-04-06 at 7 36 06 PM" src="https://user-images.githubusercontent.com/54101546/78624277-1bec5500-783e-11ea-89c6-d86c68828260.png">
<img width="1440" alt="Screen Shot 2020-04-06 at 7 36 23 PM" src="https://user-images.githubusercontent.com/54101546/78624283-1e4eaf00-783e-11ea-92f6-1201201469b7.png">
<img width="1440" alt="Screen Shot 2020-04-06 at 7 36 30 PM" src="https://user-images.githubusercontent.com/54101546/78624289-20b10900-783e-11ea-9773-6fc0240945bc.png">

I excluded most of the random numbers that printed from the screenshots

**Comment by shak360** [comment]
Looks good to me. I think you meant gamma distribution everywhere you wrote Bernoulli distribution. If you didn't, then spend some time reading what the Bernoulli distribution is for (coin flips, discrete binary events) and what the gamma distribution is for (lifetimes, events happening over continuous-time). You should be familiar with what a Bernoulli distribution looks like, how to fit a Bernoulli distribution, and how it's different from a gamma distribution. It helps me to think about coin flips with Heads being 1s and Tails being 0s.

A better way to compare the error is just to compare the error in estimating the `a` values after estimation. You'll notice that when the parameters are not fixed, the error is higher. When they are fixed the error is lower.

Recall that 'fitting' just means using data (usually random or observed randomly) to identify the parameters of the distribution that generated the data. You `fit` gamma-distributed data by trying to find the parameters of the gamma distribution that could have generated that same data. Likewise, you `fit` Bernoulli-distributed data by trying to find the parameter of the Bernoulli distribution that could have generated that data. Recall that this is just the number of Heads (the number of 1s) over the total number of coin flips (the number of 1s plus the number of 0s). There is deeper reasoning as to why this is the "best" way to fit Bernoulli data to get the Bernoulli parameter, but we can go over that later.

Fitting or estimation is the process of finding the parameters to describe the data. You can sort of think of the number of parameters we are trying to find as "degrees of freedom" in the search space of optimal parameters. In Bernoulli fitting, we only have one parameter to fit. We only have one degree of freedom to move until we reach an optimal or best parameter. In gamma fitting, we have **three** parameters we need to find values for. So we can move around the values for **three** parameters until we find an optimal solution. We have three degrees of freedom or a larger search space to find the optimal values. Given the data, there might be several good sets of three parameters that may have generated them and so the error is larger given that there is a larger set of values to choose from apart from the true set of values. When we 'freeze' or 'fix' some of the parameters this reduces the search space and lowers the degrees of freedom to just the number of unfrozen or unfixed parameters. This is why the error is lower. I know this is a hand-wavey explanation, but this is the intuition I wanted you to arrive at.
