### ISSUE TITLE
Gamma estimator

### ISSUE THREAD

**Issue by aarmey** [meyer-lab/lineage-growth#324]
https://github.com/meyer-lab/lineage-growth/blob/7bec997f3c452aa08640ce2d20a33bd21dcbed12/lineage/states/StateDistribution.py#L108

@shak360 can you explain where this expression comes from?

**Comment by aarmey** [comment]
In particular, I would expect that Halley's method would require comparing something to the data. However, this expression doesn't involve the observations in any way.

**Comment by aarmey** [comment]
Or is the data supposed to be baked into s?

**Comment by shak360** [comment]
The gamma distribution probability distribution function in the way we parameterized it looks like this:

![image](https://user-images.githubusercontent.com/20716101/82251019-577c4380-9901-11ea-94be-2a21ba860070.png)

Doing MLE on that yields the following:

![image](https://user-images.githubusercontent.com/20716101/82251242-b0e47280-9901-11ea-8ac9-a1086d67fb7e.png)

This MLE doesn't account for the participation variable or the variable that represents the expectation that an observation belongs to a state. To do so, all we have to do is raise the likelihood function to an additional variable (usually `z` or something, in the code its represented as `gammas`), and then perform MLE. This actually isn't that much more difficult because taking the log of the expression turns the variable into a coefficient and is no longer an exponent.

We can isolate the parts of the remaining function that has the observations to be:

![image](https://user-images.githubusercontent.com/20716101/82251479-22242580-9902-11ea-963d-31bdd008c159.png)

and then take the difference to create the function we want to minimize.

**Comment by shak360** [comment]
Yes, the data is baked into `s`.

**Comment by shak360** [comment]
https://github.com/meyer-lab/lineage-growth/blob/7bec997f3c452aa08640ce2d20a33bd21dcbed12/lineage/states/StateDistribution.py#L105

In this line, the observations are in `gamma_obs` and the participation variable or that `z` variable I mentioned above is stored in `gammas`. It naturally changes the normal MLE above to account for which observations belong to which states.

**Comment by aarmey** [comment]
Great. Thanks.
